# Generated by Django 5.1.3 on 2024-11-25 07:57

import django_ckeditor_5.fields
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.IntegerField(default=1, null=True)),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, null=True, quality=95, scale=None, size=[470, 315], upload_to='news/images', verbose_name='Картинка превью')),
                ('image_top', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, null=True, quality=95, scale=None, size=[1080, 450], upload_to='news/images', verbose_name='Картинка вверху статьи (1080x450)')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('slug', models.CharField(blank=True, editable=False, help_text='Если не заполнено, создается на основе поля Назавание', max_length=255, null=True, verbose_name='ЧПУ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Короткое описание')),
                ('html_content', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Контент')),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ('order_num',),
            },
        ),
    ]
