# Generated by Django 5.1.3 on 2024-11-25 08:55

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsitem',
            name='html_content',
        ),
        migrations.AddField(
            model_name='newsitem',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='content_editor',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Редактор'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='content_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Короткое описание'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Короткое описание'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
    ]
