# Generated by Django 5.1.3 on 2024-12-05 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_newsitem_html_content_newsitem_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to='news/images', verbose_name='Картинка')),
                ('news_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news.newsitem')),
            ],
        ),
    ]
