# Generated by Django 5.1.4 on 2025-01-03 09:02

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_delete_faq_callbackform_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eurRub', models.DecimalField(decimal_places=2, max_digits=6)),
                ('eurUsd', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('slug', models.CharField(blank=True, editable=False, help_text='Если не заполнено, создается на основе поля Назавание', max_length=255, null=True, verbose_name='ЧПУ')),
                ('content_editor', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Редактор')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Контент')),
                ('content_en', models.TextField(blank=True, null=True, verbose_name='Контент')),
                ('content_ru', models.TextField(blank=True, null=True, verbose_name='Контент')),
                ('is_sale', models.BooleanField(default=False, verbose_name='Это распродажа')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Акции',
                'verbose_name_plural': 'Акции',
            },
        ),
    ]
