# Generated by Django 5.1.4 on 2025-01-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_currency_sale'),
        ('shop', '0017_alter_product_price_alter_product_price_rub'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='product',
            field=models.ManyToManyField(to='shop.product'),
        ),
    ]
