# Generated by Django 5.1.3 on 2024-11-13 06:08

import django.db.models.deletion
import django_ckeditor_5.fields
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.IntegerField(default=1, null=True)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=95, scale=None, size=[60, 100], upload_to='shop/category/images')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('slug', models.CharField(blank=True, max_length=255, null=True, verbose_name='ЧПУ')),
                ('short_description', models.TextField(blank=True, verbose_name='Короткое описание')),
                ('short_description_en', models.TextField(blank=True, null=True, verbose_name='Короткое описание')),
                ('short_description_ru', models.TextField(blank=True, null=True, verbose_name='Короткое описание')),
                ('html_content', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='SEO текст')),
                ('display_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('html_content_ru', models.TextField(blank=True, null=True, verbose_name='SEO текст [RU]')),
                ('html_content_en', models.TextField(blank=True, null=True, verbose_name='SEO текст [EN]')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('order_num',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.IntegerField(default=1, null=True)),
                ('article', models.CharField(blank=True, max_length=20, null=True, verbose_name='Артикул')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна производства')),
                ('country_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна производства')),
                ('country_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна производства')),
                ('delivery', models.CharField(blank=True, max_length=100, null=True, verbose_name='Срок поставки')),
                ('delivery_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Срок поставки')),
                ('delivery_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='Срок поставки')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новинка')),
                ('is_in_stock', models.BooleanField(default=True, verbose_name='В наличии?')),
                ('is_popular', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('slug', models.CharField(blank=True, editable=False, help_text='Если не заполнено, создается на основе поля Назавание', max_length=255, null=True, verbose_name='ЧПУ')),
                ('short_description', models.TextField(blank=True, verbose_name='Короткое описание')),
                ('short_description_en', models.TextField(blank=True, null=True, verbose_name='Короткое описание')),
                ('short_description_ru', models.TextField(blank=True, null=True, verbose_name='Короткое описание')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание [RU]')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Описание [EN]')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.category')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('order_num',),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, null=True, quality=95, scale=None, size=[800, 600], upload_to='shop/product/images')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основное')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product')),
            ],
            options={
                'verbose_name': 'Доп. изображение товара',
                'verbose_name_plural': 'Доп. изображения товара',
            },
        ),
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.IntegerField(default=1, null=True)),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('price', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цена')),
                ('price_description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание цены')),
                ('price_description_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание цены')),
                ('price_description_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание цены')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='shop.product')),
            ],
            options={
                'verbose_name': 'Фасовка',
                'verbose_name_plural': 'Фасовка',
                'ordering': ('order_num',),
            },
        ),
    ]
