# Generated by Django 5.1.3 on 2024-11-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_in_stock_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productunit',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='productunit',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='productunit',
            name='price_description_en',
        ),
        migrations.RemoveField(
            model_name='productunit',
            name='price_description_ru',
        ),
        migrations.AddField(
            model_name='product',
            name='in_stock_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='В наличии'),
        ),
        migrations.AddField(
            model_name='product',
            name='in_stock_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='В наличии'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_description_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание цены'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_description_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание цены'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Фасовка'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Фасовка'),
        ),
    ]
