# Generated by Django 5.1.3 on 2024-11-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_productunit_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_opt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена опт'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фасовка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фасовка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фасовка'),
        ),
    ]
