# Generated by Django 5.1.3 on 2024-11-14 16:07

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_editor',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Редактор'),
        ),
    ]
