# Generated by Django 5.1.3 on 2024-11-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_description_editor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_rub',
            field=models.IntegerField(blank=True, default=0, verbose_name='Цена RUB'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_usd',
            field=models.IntegerField(blank=True, default=0, verbose_name='Цена $'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, default=0, verbose_name='Цена EURO'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_opt',
            field=models.IntegerField(blank=True, default=10, editable=False, verbose_name='Цена опт'),
        ),
    ]
