# Generated by Django 5.1.3 on 2024-12-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_category_top_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип товара'),
        ),
    ]
