# Generated by Django 5.1.4 on 2025-01-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_productfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Цена RUB'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_rub',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Цена EURO'),
        ),
    ]
